export const env = {
  port: Number(process.env.API_PORT ?? 4000),
  corsOrigin: process.env.CORS_ORIGIN ?? '',
  jwtSecret: process.env.JWT_SECRET ?? '',
  databaseUrl: process.env.DATABASE_URL ?? '',
  redisUrl: process.env.REDIS_URL ?? '',
  elasticsearchNode: process.env.ELASTICSEARCH_NODE ?? '',
  webAppBaseUrl: process.env.WEB_APP_BASE_URL ?? '',
  puppeteerExecutablePath: process.env.PUPPETEER_EXECUTABLE_PATH ?? '',
  authCodeTtlMinutes: Number(process.env.AUTH_CODE_TTL_MINUTES ?? 5),
  authCodeLength: Number(process.env.AUTH_CODE_LENGTH ?? 6),
  authCodeSecret: process.env.AUTH_CODE_SECRET ?? process.env.JWT_SECRET ?? '',
  aliyunSmsEndpoint: process.env.ALIYUN_SMS_ENDPOINT ?? '',
  aliyunSmsAccessKeyId: process.env.ALIYUN_SMS_ACCESS_KEY_ID ?? '',
  aliyunSmsAccessKeySecret: process.env.ALIYUN_SMS_ACCESS_KEY_SECRET ?? '',
  aliyunSmsSignName: process.env.ALIYUN_SMS_SIGN_NAME ?? '',
  aliyunSmsTemplateCode: process.env.ALIYUN_SMS_TEMPLATE_CODE ?? '',
  aliyunSmsTemplateParamName: process.env.ALIYUN_SMS_TEMPLATE_PARAM_NAME ?? '',
  ossRegion: process.env.OSS_REGION ?? '',
  ossEndpoint: process.env.OSS_ENDPOINT ?? '',
  ossBucket: process.env.OSS_BUCKET ?? '',
  ossAccessKeyId: process.env.OSS_ACCESS_KEY_ID ?? '',
  ossAccessKeySecret: process.env.OSS_ACCESS_KEY_SECRET ?? '',
  ossStsRoleArn: process.env.OSS_STS_ROLE_ARN ?? '',
  ossStsEndpoint: process.env.OSS_STS_ENDPOINT ?? '',
  ossUploadExpireSeconds: Number(process.env.OSS_UPLOAD_EXPIRE_SECONDS ?? 900),
  ossSignExpireSeconds: Number(process.env.OSS_SIGN_EXPIRE_SECONDS ?? 1800),
  ossCustomDomain: process.env.OSS_CUSTOM_DOMAIN ?? '',
  wechatPayGatewayUrl: process.env.WECHAT_PAY_GATEWAY_URL ?? '',
  wechatPayAppId: process.env.WECHAT_PAY_APP_ID ?? '',
  wechatPayAppSecret: process.env.WECHAT_PAY_APP_SECRET ?? '',
  wechatPayNotifyUrl: process.env.WECHAT_PAY_NOTIFY_URL ?? '',
  wechatPayRefundNotifyUrl: process.env.WECHAT_PAY_REFUND_NOTIFY_URL ?? '',
  wechatPayOrderExpireMinutes: Number(process.env.WECHAT_PAY_ORDER_EXPIRE_MINUTES ?? 15),
};
