export const JOBS_RECOMMENDATION_VERSION = 'v4-standardized';
export const JOBS_RECOMMENDATION_CACHE_TTL_MS = 10 * 60 * 1000;
export const JOBS_RECOMMENDATION_MAX_PREFERENCE_KEYWORDS = 5;
export const JOBS_RECOMMENDATION_THREE_DIMENSION_COMBINATION_LIMIT = 125;
export const JOBS_RECOMMENDATION_TWO_DIMENSION_COMBINATION_LIMIT = 25;
export const JOBS_RECOMMENDATION_ONE_DIMENSION_COMBINATION_LIMIT = 5;
export const JOBS_RECOMMENDATION_COMBINATION_BATCH_SIZE = 20;
export const JOBS_RECOMMENDATION_PER_COMBINATION_TAKE = 12;
export const JOBS_RECOMMENDATION_PRIMARY_CANDIDATE_LIMIT = 220;
export const JOBS_RECOMMENDATION_FALLBACK_CANDIDATE_LIMIT = 120;
export const JOBS_RECOMMENDATION_MAX_CANDIDATES = 500;
export const JOBS_RECOMMENDATION_REASON_LIMIT = 2;
export const JOBS_RECOMMENDATION_PARENT_LOCATION_LOOKBACK_DAYS = 90;
export const JOBS_RECOMMENDATION_FALLBACK_FRESH_DAYS = 7;
export const JOBS_RECOMMENDATION_FALLBACK_ENTERPRISE_NATURES = ['央企', '国企'] as const;
export const JOBS_RECOMMENDATION_EFFECTIVE_PROGRESS_STATUSES = [
  '已投递',
  '已笔试',
  '已面试',
  '已录用',
  '已拒绝',
  '已取消',
  '其他',
] as const;
export const JOB_ACCESS_CLICK_ACTION_TYPES = ['view_announcement', 'deliver', 'view_referral', 'update_progress'] as const;
